Repository fykaa/Sample-Portfolio-for-Learners, pull requests merged in 2022-10, with the labels that each got.

#57 MODIFY FORM PAGE UI
  pages/learnings/form.html
  pages/learnings/styles/form.css
Labels: hacktoberfest, hacktoberfest-accepted

#64 feat: added link to logo
  index.html
  styling.css
Labels: hacktoberfest, hacktoberfest-accepted

#66 ref: cleared the commented code from styling.css
  styling.css
Labels: hacktoberfest, hacktoberfest-accepted

#73 linked projects to homepage
  assets/main home page/Amit.png
  assets/main home page/Aryan.png
  assets/main home page/Bank-project.png
  assets/main home page/Business-card-main.png
  assets/main home page/Static card.png
  assets/main home page/Suryansh Card.png
  assets/main home page/Vigenere Cipher.png
  assets/main home page/animesite.png
  assets/main home page/portfolio.png
  assets/main home page/sample-projects.png
  assets/main home page/spotify-clone.png
  index.html
  styling.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#83 added a tribute page in projects
  projects/Tribute-Page/Images/Certh rune no..png
  projects/Tribute-Page/Images/Der Berggeist.jpg
  projects/Tribute-Page/Images/Gallery-1.jpg
  projects/Tribute-Page/Images/Gallery-2.jpg
  projects/Tribute-Page/Images/Gallery-3.jpg
  projects/Tribute-Page/Images/Gallery-4.jpg
  projects/Tribute-Page/Images/Gallery-5.jpg
  projects/Tribute-Page/Images/Gallery-6.png
  projects/Tribute-Page/Images/Gallery-7.jpg
  projects/Tribute-Page/Images/Gallery-8.jpg
  projects/Tribute-Page/Images/Gandalf-2.JPG
  projects/Tribute-Page/Images/Gandalf-feature.jpg
  projects/Tribute-Page/Images/Gandalf.jpg
  projects/Tribute-Page/Images/Ian McKellen.jpg
  projects/Tribute-Page/Images/Odin.jpg
  projects/Tribute-Page/Images/Vainamoinen.jpg
  projects/Tribute-Page/Images/Virgil.jpg
  projects/Tribute-Page/index.html
  projects/Tribute-Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#20 Add a favicon site
  pages/learnings/icons.html
Labels: hacktoberfest

#95 changed contact-us section css
  styling.css
Labels: hacktoberfest, hacktoberfest-accepted
